"use client";

import {
  ArrowRight, BarChart3, CalendarDays, Check, ChevronDown, Download,
  Eye, Frame, Grid2X2, ImagePlus, MapPin, Menu, MoreHorizontal,
  Plus, QrCode, ScanLine, Search, Send, Settings, Sparkles, Ticket,
  Type, Users, X,
} from "lucide-react";
import { type CSSProperties, useEffect, useMemo, useState } from "react";

type View = "discover" | "tickets" | "events" | "studio" | "guests" | "checkin" | "analytics";
type EventItem = { id:number; title:string; company:string; date:string; day:string; month:string; place:string; city:string; category:string; access:string; attendees:number; capacity:number; tone:string; image:string };
type WebMcpTool = { name:string; title:string; description:string; inputSchema:object; annotations?:{readOnlyHint?:boolean;untrustedContentHint?:boolean}; execute:(input:unknown)=>unknown };
declare global { interface Document { modelContext?: { registerTool:(tool:WebMcpTool,options?:{signal?:AbortSignal})=>void|Promise<void> } } }

const events: EventItem[] = [
  { id:1, title:"Future of Work / Almaty", company:"Orbit Labs", date:"24 сентября · 18:30", day:"24", month:"СЕН", place:"Terrenkur Hall", city:"Алматы", category:"Технологии", access:"По регистрации", attendees:184, capacity:240, tone:"cobalt", image:"/event-design.png" },
  { id:2, title:"After Hours: Product People", company:"Northstar Collective", date:"27 сентября · 20:00", day:"27", month:"СЕН", place:"Rooftop 18", city:"Астана", category:"Нетворкинг", access:"По приглашению", attendees:76, capacity:90, tone:"coral", image:"/event-rooftop.png" },
  { id:3, title:"Design Systems Picnic", company:"Forma Bureau", date:"4 октября · 12:00", day:"04", month:"ОКТ", place:"Ботанический сад", city:"Алматы", category:"Дизайн", access:"Открытое событие", attendees:129, capacity:320, tone:"lime", image:"/event-design.png" },
];

const guests = [
  { name:"Алина Ибраева", email:"alina@orbit.kz", status:"Подтверждён", initials:"АИ" },
  { name:"Марк Соколов", email:"mark@northstar.team", status:"Приглашён", initials:"МС" },
  { name:"Дана Ахметова", email:"dana@forma.studio", status:"Лист ожидания", initials:"ДА" },
  { name:"Илья Ли", email:"ilya@orbit.kz", status:"Подтверждён", initials:"ИЛ" },
];

const primaryNav = [{ id:"discover" as View, label:"Афиша", icon:Grid2X2 }, { id:"tickets" as View, label:"Мои билеты", icon:Ticket }];
const orgNav = [{ id:"events" as View, label:"События", icon:CalendarDays }, { id:"studio" as View, label:"Студия приглашений", icon:Frame }, { id:"guests" as View, label:"Гости", icon:Users }, { id:"checkin" as View, label:"Check-in", icon:ScanLine }, { id:"analytics" as View, label:"Аналитика", icon:BarChart3 }];

function Logo(){ return <span className="logo"><b>E</b><i/><em/></span>; }

function Sidebar({view, setView, open, close}:{view:View;setView:(v:View)=>void;open:boolean;close:()=>void}){
  const go=(id:View)=>{setView(id);close();};
  return <aside className={`sidebar ${open?"open":""}`}><div className="brand"><Logo/><strong>evently</strong></div><button className="close" onClick={close}><X/></button><nav><small>Для меня</small>{primaryNav.map(({id,label,icon:Icon})=><button key={id} className={view===id?"active":""} onClick={()=>go(id)}><Icon/>{label}</button>)}<small>Orbit Labs</small>{orgNav.map(({id,label,icon:Icon})=><button key={id} className={view===id?"active":""} onClick={()=>go(id)}><Icon/>{label}</button>)}</nav><div className="org"><span>OL</span><p><b>Orbit Labs</b><small>12 организаторов</small></p><ChevronDown/></div></aside>;
}

function Header({onMenu}:{onMenu:()=>void}){return <header className="topbar"><button className="hamb" onClick={onMenu}><Menu/></button><label className="search"><Search/><input placeholder="Найти событие, компанию или город"/></label><button className="circle"><Settings/></button><button className="user"><span>RK</span><p><b>Руслан</b><small>Организатор</small></p><ChevronDown/></button></header>}

function Discover({selected,setSelected,onRegister}:{selected:EventItem;setSelected:(e:EventItem)=>void;onRegister:()=>void}){
  const [filter,setFilter]=useState("Все события");
  const visible=events.filter(e=>filter==="Все события"||(filter==="Моя компания"&&e.company==="Orbit Labs")||e.category===filter);
  return <div className="discover-grid"><section className="page discover"><div className="micro"><span>АЛМАТЫ / АСТАНА</span><span>СЕНТЯБРЬ — ОКТЯБРЬ</span></div><div className="hero"><div><h1>Куда пойдём<br/>на этой неделе?</h1><p>События от компаний, команд и людей, за которыми хочется следить.</p></div><span className="sticker">CURATED<br/>FOR YOU <Sparkles/></span></div><div className="filters">{["Все события","Моя компания","Дизайн","Технологии","Нетворкинг"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="event-list">{visible.map(event=><button className={`event-card ${selected.id===event.id?"selected":""}`} key={event.id} onClick={()=>setSelected(event)}><div className={`event-art ${event.tone}`} style={{backgroundImage:`linear-gradient(25deg,rgba(20,18,30,.38),transparent),url(${event.image})`}}><span className="date"><b>{event.day}</b><small>{event.month}</small></span><em>{event.company}</em></div><div className="event-copy"><div className="tags"><span>{event.category}</span><span>{event.access}</span></div><h2>{event.title}</h2><p><CalendarDays/>{event.date}</p><p><MapPin/>{event.place}, {event.city}</p><div className="capacity"><i><b style={{width:`${event.attendees/event.capacity*100}%`}}/></i><small>{event.attendees} из {event.capacity} мест</small></div></div><ArrowRight className="arrow"/></button>)}</div></section><aside className="detail"><button className="dots"><MoreHorizontal/></button><div className={`poster ${selected.tone}`} style={{backgroundImage:`linear-gradient(15deg,rgba(18,16,28,.58),transparent),url(${selected.image})`}}><span>{selected.company}</span><strong>{selected.title}</strong><small>{selected.date}</small></div><div className="detail-copy"><div className="tags"><span>{selected.category}</span><span>{selected.access}</span></div><h2>{selected.title}</h2><p>Разговоры без скучных панелей, новые знакомства и идеи, которые хочется унести с собой.</p><dl><div><dt>Когда</dt><dd>{selected.date}</dd></div><div><dt>Где</dt><dd>{selected.place}<small>{selected.city}</small></dd></div><div><dt>Организатор</dt><dd>{selected.company}<small>Подтверждённая компания</small></dd></div></dl><button className="cta" onClick={onRegister}>Получить билет <ArrowRight/></button><small className="note">Регистрация займёт меньше минуты</small></div></aside></div>;
}

function TicketView({event}:{event:EventItem}){
  const savePng=()=>{const c=document.createElement("canvas");c.width=1080;c.height=1350;const x=c.getContext("2d");if(!x)return;x.fillStyle="#19181f";x.fillRect(0,0,c.width,c.height);x.fillStyle="#d8ff45";x.beginPath();x.arc(940,320,250,0,Math.PI*2);x.fill();x.fillStyle="#fff";x.font="900 82px Arial";x.fillText(event.title.toUpperCase(),70,520,900);x.font="700 32px Arial";x.fillText(event.date,70,650);x.fillText(`${event.place}, ${event.city}`,70,710);x.fillText("GUEST — РУСЛАН К.",70,1160);const a=document.createElement("a");a.download="evently-ticket.png";a.href=c.toDataURL();a.click()};
  return <section className="page ticket-page"><span className="kicker">МОИ БИЛЕТЫ / 01</span><h1>До встречи<br/>на событии.</h1><div className="ticket-layout"><article className="ticket-card"><div className="ticket-head"><Logo/><span>CONFIRMED</span></div><div><small>ORBIT LABS ПРЕДСТАВЛЯЕТ</small><h2>{event.title}</h2></div><div className="ticket-meta"><span><small>ДАТА</small>{event.date}</span><span><small>МЕСТО</small>{event.place}</span></div><div className="ticket-meta"><span><small>ГОСТЬ</small>Руслан К.</span><span><small>БИЛЕТ</small>EVT–2409–0184</span></div><div className="qr"><QrCode/></div><p>Покажите QR-код сотруднику на входе</p></article><div className="ticket-actions"><h3>Билет готов</h3><p>Сохраните его на телефон или распечатайте. QR-код одинаковый во всех форматах.</p><button onClick={()=>window.print()}><Download/> Скачать PDF</button><button onClick={savePng}><ImagePlus/> Сохранить PNG</button><button onClick={()=>alert("Билет отправлен на email")}><Send/> Отправить на email</button></div></div></section>;
}

function Studio(){const [template,setTemplate]=useState(0);const [accent,setAccent]=useState("#d8ff45");const [size,setSize]=useState(54);return <section className="studio"><header><div><span className="kicker">СТУДИЯ ПРИГЛАШЕНИЙ</span><h1>Future of Work</h1></div><div><button className="secondary"><Eye/> Предпросмотр</button><button className="primary"><Check/> Сохранено</button></div></header><div className="studio-grid"><aside className="templates"><h3>Шаблоны</h3><div>{["Pulse","Afterdark","Gallery","Minimal"].map((x,i)=><button key={x} className={template===i?"active":""} onClick={()=>setTemplate(i)}><i className={`mini m${i}`}/>{x}</button>)}</div><hr/><h3>Добавить</h3><div className="tools"><button><Type/>Текст</button><button><ImagePlus/>Фото</button><button><QrCode/>QR-код</button><button><Grid2X2/>Фигура</button></div></aside><main className="canvas-area"><div className={`invite t${template}`} style={{"--accent":accent} as CSSProperties}><span>ORBIT LABS</span><em>01 / 04</em><div contentEditable suppressContentEditableWarning style={{fontSize:size}}>FUTURE<br/>OF WORK</div><p>24.09 · TERRENKUR HALL<br/>ALMATY · 18:30</p><small>INVITE / {"{{guest_name}}"}</small></div></main><aside className="props"><div className="prop-tabs"><button className="active">Дизайн</button><button>Данные</button></div><label>Текст<input defaultValue="FUTURE OF WORK"/></label><label>Размер<div className="range"><input type="range" min="34" max="80" value={size} onChange={e=>setSize(+e.target.value)}/><span>{size}</span></div></label><label>Акцент<div className="swatches">{["#d8ff45","#ff6846","#6c57ff","#63e6be"].map(c=><button key={c} className={accent===c?"active":""} style={{background:c}} onClick={()=>setAccent(c)}/>)}</div></label><hr/><h3>Слои</h3><button className="layer active"><Type/>Заголовок</button><button className="layer"><QrCode/>QR-код</button><button className="layer"><Frame/>Детали</button></aside></div></section>}

function PageHead({title,text,action}:{title:string;text:string;action:string}){return <div className="data-head"><div><span className="kicker">ORBIT LABS / ПАНЕЛЬ</span><h1>{title}</h1><p>{text}</p></div><button className="primary"><Plus/>{action}</button></div>}
function EventsView(){return <section className="page data-page"><PageHead title="События" text="Управляйте публикациями, регистрациями и программой." action="Создать"/><Metrics/><div className="data-card"><div className="card-head"><span><CalendarDays/>Активные события</span><button>Все события <ArrowRight/></button></div>{events.map(e=><div className="table-row" key={e.id}><span className={`tiny ${e.tone}`}>{e.day}</span><span><b>{e.title}</b><small>{e.date}</small></span><span><small>ГОСТИ</small>{e.attendees} / {e.capacity}</span><em>Опубликовано</em><button><MoreHorizontal/></button></div>)}</div></section>}
function Metrics(){return <div className="metrics"><article><small>РЕГИСТРАЦИИ</small><b>1 248</b><span>+18% за 30 дней</span></article><article><small>CHECK-IN</small><b>82%</b><span>выше среднего</span></article><article><small>ОТКРЫТИЯ EMAIL</small><b>71%</b><span>896 приглашений</span></article></div>}
function GuestsView(){const [q,setQ]=useState("");const list=guests.filter(g=>(g.name+g.email).toLowerCase().includes(q.toLowerCase()));return <section className="page data-page"><PageHead title="Гости" text="Единый список приглашённых и статусы регистрации." action="Импорт CSV"/><div className="guest-tools"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Имя или email"/></label><button><Download/>Экспорт</button></div><div className="data-card"><div className="card-head"><span><Users/>{list.length} гостя</span><button>Настроить поля <ArrowRight/></button></div>{list.map(g=><div className="guest-row" key={g.email}><span className="avatar">{g.initials}</span><span><b>{g.name}</b><small>{g.email}</small></span><em className={g.status==="Подтверждён"?"ok":""}>{g.status}</em><button><MoreHorizontal/></button></div>)}</div></section>}
function CheckinView(){const [checked,setChecked]=useState([guests[0].name]);const toggle=(n:string)=>setChecked(v=>v.includes(n)?v.filter(x=>x!==n):[...v,n]);return <section className="page data-page"><PageHead title="Check-in" text="Сканируйте QR или найдите гостя вручную." action="Добавить сотрудника"/><div className="check-grid"><article className="scanner"><div><QrCode/><b>Наведите камеру на QR</b></div><button className="primary" onClick={()=>alert("Камера откроется на мобильном устройстве")}><ScanLine/>Открыть сканер</button><p>Последняя синхронизация: только что</p></article><article className="check-list"><div className="card-head"><span><Users/>На площадке</span><b>{checked.length} / {guests.length}</b></div>{guests.map(g=><button key={g.name} onClick={()=>toggle(g.name)}><span className="avatar">{g.initials}</span><span><b>{g.name}</b><small>{g.email}</small></span><em className={checked.includes(g.name)?"checked":""}>{checked.includes(g.name)?<><Check/>Вошёл</>:"Отметить"}</em></button>)}</article></div></section>}
function AnalyticsView(){const funnel:[[string,number,number],[string,number,number],[string,number,number],[string,number,number]]=[["Отправлено",896,100],["Открыто",636,71],["Регистрация",418,47],["Пришли",343,38]];return <section className="page data-page"><PageHead title="Аналитика" text="Путь гостя от приглашения до посещения." action="Экспорт CSV"/><Metrics/><div className="analytics"><article className="funnel"><div className="card-head"><span><BarChart3/>Воронка приглашения</span><small>30 дней</small></div><div>{funnel.map(([n,v,w])=><p key={n}><span><b>{n}</b><strong>{v}</strong></span><i><em style={{width:`${w}%`}}/></i></p>)}</div></article><article className="pulse"><small>САМЫЙ АКТИВНЫЙ ДЕНЬ</small><b>24</b><h3>сентября</h3><p>68% гостей приходят в первые 25 минут после открытия дверей.</p><span>18:00 → 18:25</span></article></div></section>}

export default function Home(){const [view,setView]=useState<View>("discover");const [selected,setSelected]=useState(events[0]);const [menu,setMenu]=useState(false);const current=useMemo(()=>selected,[selected]);useEffect(()=>{if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>undefined);const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=(tool:WebMcpTool)=>{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>undefined)};register({name:"list_evently_events",title:"List Evently events",description:"Read the events currently available in the Evently catalog.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>events.map(({id,title,company,date,city,category,access})=>({id,title,company,date,city,category,access}))});register({name:"register_for_evently_event",title:"Register for an Evently event",description:"Register for a catalog event by numeric ID and open its ticket in the visible Evently interface.",inputSchema:{type:"object",properties:{eventId:{type:"number"}},required:["eventId"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input)=>{const id=typeof input==="object"&&input!==null&&"eventId" in input?Number((input as {eventId:unknown}).eventId):NaN;const event=events.find(item=>item.id===id);if(!event)throw new Error("Unknown eventId");setSelected(event);setView("tickets");return {status:"confirmed",eventId:event.id,title:event.title,ticket:"EVT-2409-0184"}}});return()=>lifecycle.abort()},[]);return <main className="app"><Sidebar view={view} setView={setView} open={menu} close={()=>setMenu(false)}/>{menu&&<button className="scrim" onClick={()=>setMenu(false)}/>}<div className="main"><Header onMenu={()=>setMenu(true)}/>{view==="discover"&&<Discover selected={current} setSelected={setSelected} onRegister={()=>setView("tickets")}/>} {view==="tickets"&&<TicketView event={current}/>} {view==="studio"&&<Studio/>} {view==="events"&&<EventsView/>} {view==="guests"&&<GuestsView/>} {view==="checkin"&&<CheckinView/>} {view==="analytics"&&<AnalyticsView/>}</div></main>}
